name: 'zoom_customer_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target"]

models:
  zoom_customer_analytics:
    materialized: table
    bronze:
      +schema: bronze
