name: 'Zoom_Customer_Analytics'
version: '1.0.0'
config-version: 2

profile: 'Zoom_Customer_Analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Zoom_Customer_Analytics:
    +materialized: table
    +on_schema_change: "fail"
    silver:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'si_audit_log' %}
        INSERT INTO {{ ref('si_audit_log') }} (source_table, load_timestamp, processed_by, processing_time, status)
        VALUES ('{{ this.name }}', CURRENT_TIMESTAMP(), 'dbt_transformation', 0, 'STARTED')
        {% endif %}
      +post-hook: |
        {% if this.name != 'si_audit_log' %}
        UPDATE {{ ref('si_audit_log') }} 
        SET status = 'COMPLETED', processing_time = DATEDIFF('second', load_timestamp, CURRENT_TIMESTAMP())
        WHERE source_table = '{{ this.name }}' AND status = 'STARTED'
        {% endif %}
