version: 2

models:
        
  - name: go_meeting_facts
    description: "Gold layer meeting facts table"
        
  - name: go_participant_facts
    description: "Gold layer participant facts table"
        
  - name: go_webinar_facts
    description: "Gold layer webinar facts table"
        
  - name: go_billing_facts
    description: "Gold layer billing facts table"
        
  - name: go_usage_facts
    description: "Gold layer usage facts table"
        
  - name: go_quality_facts
    description: "Gold layer quality facts table"
