{{
  config(
    materialized='table',
    tags=['audit', 'bronze']
  )
}}

-- Audit log table for tracking bronze layer transformations
-- This table must be created first before other bronze models

SELECT 
    CAST(NULL AS NUMBER) AS AUDIT_ID,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_LAYER,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_TABLE,
    CAST(NULL AS VARCHAR(255)) AS TARGET_LAYER,
    CAST(NULL AS VARCHAR(255)) AS TARGET_TABLE,
    CAST(NULL AS VARCHAR(50)) AS LOAD_TYPE,
    CAST(NULL AS TIMESTAMP_NTZ) AS LOAD_START_TIME,
    CAST(NULL AS TIMESTAMP_NTZ) AS LOAD_END_TIME,
    CAST(NULL AS NUMBER) AS RECORD_COUNT_LOADED,
    CAST(NULL AS VARCHAR(50)) AS STATUS,
    CAST(NULL AS VARCHAR(1000)) AS ERROR_MESSAGE,
    CAST(NULL AS VARCHAR(255)) AS RUN_ID,
    CAST(NULL AS VARCHAR(255)) AS CREATED_BY,
    CAST(NULL AS TIMESTAMP_NTZ) AS CREATED_AT
WHERE 1=0

UNION ALL

-- Initial audit log entry
SELECT 
    1 AS AUDIT_ID,
    'SYSTEM' AS SOURCE_LAYER,
    'AUDIT_LOG_BZ' AS SOURCE_TABLE,
    'BRONZE' AS TARGET_LAYER,
    'AUDIT_LOG_BZ' AS TARGET_TABLE,
    'INITIAL' AS LOAD_TYPE,
    CURRENT_TIMESTAMP AS LOAD_START_TIME,
    CURRENT_TIMESTAMP AS LOAD_END_TIME,
    1 AS RECORD_COUNT_LOADED,
    'SUCCESS' AS STATUS,
    NULL AS ERROR_MESSAGE,
    '{{ invocation_id }}' AS RUN_ID,
    CURRENT_USER() AS CREATED_BY,
    CURRENT_TIMESTAMP AS CREATED_AT
