{{ config(
    materialized='table'
) }}

-- Audit Log Table for Bronze Layer
SELECT 
    1 as AUDIT_ID,
    'SYSTEM' as SOURCE_LAYER,
    'SYSTEM_INIT' as SOURCE_TABLE,
    'BRONZE' as TARGET_LAYER,
    'AUDIT_LOG_BZ' as TARGET_TABLE,
    'FULL' as LOAD_TYPE,
    CURRENT_TIMESTAMP as LOAD_START_TIME,
    CURRENT_TIMESTAMP as LOAD_END_TIME,
    0 as RECORD_COUNT_LOADED,
    'SUCCESS' as STATUS,
    NULL as ERROR_MESSAGE,
    'init' as RUN_ID,
    CURRENT_USER() as CREATED_BY,
    CURRENT_TIMESTAMP as CREATED_AT
WHERE FALSE
