version: 2

sources:
  - name: raw
    description: "Raw data from Zoom platform"
    database: zoom_customer_analytics
    schema: raw
    tables:
      - name: users
        description: "Raw users data from Zoom"
      - name: meetings
        description: "Raw meetings data from Zoom"
